#!/bin/sh

rm -fv *.crop
rm -fv *.empty
find individual-characters -type f -print0|xargs -r -0 rm -v
git checkout individual-characters/.gitignore
rm -v poster-complete-*
rm -v poster-inline-breaks-*
rm -v U-*.png
